---
- name: copy files to remote server
  hosts: all

  tasks:
  - name: copy files
    copy:
      src: /home/vagrant/myfile.txt
      dest: /tmp/
      owner: vagrant
      group: vagrant
#     mode: 0777
      mode: ugo=rw
      backup: true
