---
- name: User management
  hosts: webservers
  become: yes

  tasks:
  - name: User creation
    user:
      name: mpm01
      comment: new user in mpm team
      shell: /bin/bash

# use the following commands to verify the results
# $cat /etc/password
# $id mpm01
# $groupadd mpmtech
# $cat /etc/group

# if you want to add the user to new group or groups
#     group: mpmtech
      groups: mpmtech,mpmprod

# if you want to delete the user
      state: absent
      remove: yes          #removes user directory and data
