---
- name: Set Password
  hosts: all
  become: yes

  tasks:
  - name: Set Password
    user:
      name: mpm01
      update_password: always
#     password: abcd123  # this passwd is not hashed, will give warning
      password: "{{'abcd123' | password_hash('sha512')}}" 


# to check the effect in remote server use following commands
# $su - mpm01
# $whoami
