---
- name: Kill a process
  hosts: all
  become: yes

  tasks:
  - name: Find a process and kill 
    ignore_errors: yes
    shell: "pgrep ngnix | xargs kill"
  
  - name: Restart process
    service:
      name: nginx
      state: started
