---
- name: Install services
  hosts: all
  become: true
  vars:
    - apps: [yum,httpd,vim,telnet]

  tasks:
  - name: Installing nginx
    yum:
      name: "{{ item }}"
      state: present
    tags: i-nginx
    with_items: "{{ apps }}"
