---
- name: install and start nginx
  hosts: all
  become: true

  tasks:
  - name: update yum package
    yum:
     name: "*"
     state: present

  - name: "this installs yum install epel-release"
    yum:
     name: epel-release
     state: present

  - name: installing nginx
    yum:
     name: nginx
     state: present

  - name: starting nginx service
    service:
     name: nginx
     state: started
     enabled: true
   
