---
- name: install and start nginx
  hosts: localhost
  become: true

  tasks:
  - name: installing nginx
    yum:
     name: nginx
     state: present

  - name: starting nginx service
    service:
     name: nginx
     state: started
     enabled: true
   
