---
- name: Install HTTPD using Ansible Playbook
  hosts: webservers #here ensure that node instance name is correct or not 
  become: true
  tasks:
    - name: Install HTTPD package
      package:
        name: httpd
        state: present
    - name: Start HTTPD service
      service:
        name: httpd
        state: started
        enabled: yes
